### ISSUE TITLE
PG : no attribute 'output'

### ISSUE THREAD

**Issue by igeofr** [Guts/DicoGIS#19]
INFO:DicoGIS:Operating system: Linux-5.4.0-53-generic-x86_64-with-glibc2.29
INFO:DicoGIS:Language switched to: FR
INFO:DicoGIS:Excel file created
INFO:DicoGIS:PROCESS LAUNCHED: SGBD
INFO:DicoGIS:Required fields are OK.
INFO:DicoGIS:No proxy configured.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "dicogis/DicoGIS.py", line 275, in <lambda>
    command=lambda: self.process(),
  File "dicogis/DicoGIS.py", line 687, in process
    self.check_fields()
  File "dicogis/DicoGIS.py", line 1213, in check_fields
    self.test_connection()
  File "dicogis/DicoGIS.py", line 1265, in test_connection
    self.output.delete(0, END)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2345, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'output'

**Comment by Guts** [comment]
Thanks for your interest and to take the time to report!
