### ISSUE TITLE
XLS maximum row reached

### ISSUE THREAD

**Issue by pelord** [Guts/DicoGIS#4]
On multiple features, maximum row of XLS is reach. Working on xlsx would extend maximum of lines to 1 million...

Here the log traceback

Exception in Tkinter callback
Traceback (most recent call last):
  File "Tkinter.pyo", line 1532, in **call**
  File "DicoGIS.py", line 493, in <lambda>
  File "DicoGIS.py", line 904, in process
  File "DicoGIS.py", line 1023, in process_files
  File "DicoGIS.py", line 1838, in dictionarize_vectors
  File "xlwt\Worksheet.pyo", line 1078, in row
  File "xlwt\Row.pyo", line 42, in **init**
ValueError: row index (65536) not an int in range(65536)

**Comment by Guts** [comment]
Indeed. I'm planning to replace xlwt by [openpyxl](https://bitbucket.org/openpyxl/openpyxl/overview).
It should fix this issue.

**Comment by pelord** [comment]
Thanks, let us know when the issue is fixed.

**Comment by Guts** [comment]
Should be fixed with #17 which is planned now :)
