### ISSUE TITLE
version 2.1.0 beta 3 don't work on windows xp

### ISSUE THREAD

**Issue by aitorfreire** [Guts/DicoGIS#5]
Version **2.1.0 beta 3** don't work on *windows xp sp3*. This is the content of the DicoGIS.exe.log file:
Traceback (most recent call last):
  File "DicoGIS.py", line 60, in <module>
  File "gdal.pyo", line 2, in <module>
  File "osgeo\__init__.pyo", line 21, in <module>
  File "osgeo\__init__.pyo", line 13, in swig_import_helper
  File "osgeo\_gdal.pyo", line 12, in <module>
  File "osgeo\_gdal.pyo", line 10, in __load
ImportError: DLL load failed: No se encontró el proceso especificado.
I try it on windows 8.1 and it works fine.
Saludos!

**Comment by Guts** [comment]
Gracias por señalar pero no tengo Windows XP y me parece complicado solvar problemas sobre un sistema no mas mantenido por su editor.

Ademas, me parece un error gdal. Voy a intentar compilar DicoGIS con la ultima versión de gdal. A ver si corrige el problema.
